// all recipes
GET http://localhost:3001/recipes


###
//one recipe
GET http://localhost:3001/recipes/63ef757a73c241483806b6a7


###
// add recipe
POST http://localhost:3001/recipes 
Content-Type: application/json

{
    "name": "Amazing Recipe",
    "time": 40,
    "steps": "It takes one to know one",
    "ingredients": ["how will this work??", "ingredient1", "ingredient2"]
}


###
DELETE http://localhost:3001/recipes/63ef719940c668c6406cc75f


###

PATCH http://localhost:3001/recipes/63ef757a73c241483806b6a7
Content-Type: application/json

{
    "name": "New GAG"
}